version: '3'

services:

  zookeeper:
    image: strimzi/kafka:0.14.0-kafka-2.3.0
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs

  infinispan:
    image: docker.io/jboss/infinispan-server:10.1
    command: [
      "sh", "-c",
      "./bin/launch.sh"
    ]
    ports:
      - "11222:11222"
    environment:
      USER: infinispan
      PASS: infinispan

  keycloak:
    image: docker.io/jboss/keycloak:9.0.0
    command: [
      "-b",
      "0.0.0.0"
    ]
    ports:
      - "8280:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/kogito-realm.json
    volumes:
      - ./kogito-realm.json:/tmp/kogito-realm.json
  
  dataindex:
    image: quay.io/kiegroup/kogito-data-index:0.9.0-rc1
    network_mode: 'host' 
    restart: on-failure
    ports:
      - "8180:8180"
    depends_on:
      - infinispan
    environment:
      INFINISPAN_AUTHREALM: default 
      INFINISPAN_PASSWORD: infinispan 
      INFINISPAN_USERNAME: infinispan 
      INFINISPAN_SASLMECHANISM: PLAIN 
      INFINISPAN_USEAUTH: "true"
      KOGITO_DATA_INDEX_HTTP_PORT: 8180

  management:
    image: quay.io/kiegroup/kogito-management-console:0.9.0-rc1
    network_mode: 'host'
    restart: on-failure
    ports:
      - "8380:8380"
    depends_on:
      - dataindex
    environment:
      KOGITO_DATA_INDEX_PROPS: "-Dquarkus.http.port=8380"
      KOGITO_DATAINDEX_HTTP_URL: "http://localhost:8180"

  kafka:
    image: strimzi/kafka:0.14.0-kafka-2.3.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "kafka:1:1:compact"
