apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: keycloak-db-secret
  namespace: {{ .Values.global.rhsso.namespace }}
  labels: {{- include "commonLabels" . | indent 4 }}
stringData:
  POSTGRES_DATABASE: {{ .Values.database.name }}
  POSTGRES_EXTERNAL_ADDRESS: {{ .Values.database.host }}
  POSTGRES_EXTERNAL_PORT: {{ .Values.database.port | quote }}
  POSTGRES_HOST: keycloak-{{ .Values.database.driver }}
  POSTGRES_PASSWORD: {{ .Values.database.password }}
  POSTGRES_SUPERUSER: "true"
  POSTGRES_USERNAME: {{ .Values.database.username }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rhsso-rhpam-admin-secret
  namespace: {{ .Values.global.rhsso.namespace }}
  labels: {{- include "commonLabels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
stringData:
  ADMIN_USERNAME: {{ .Values.rhpam.admin.username }}
  ADMIN_PASSWORD: {{ .Values.rhpam.admin.password }}