# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build CI with Maven and Node for bdd-ui

on:
  push:
    paths:
      - .github/workflows/build-bdd-ui.yaml
      - bdd-ui/**
  pull_request:
    paths:
      - .github/workflows/build-bdd-ui.yaml
      - bdd-ui/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-bdd-ui-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run ShellCheck
        if: matrix.os == 'ubuntu-latest'
        uses: ludeeus/action-shellcheck@master
        with:
          ignore: bcgithook kogito-quick-start-workshop offliner-maven-plugin pam-eap-setup pam-quick-examples pam-vagrant

      - name: Build bdd-ui/maven-java-bdd-demo
        run: mvn -B clean install -f bdd-ui/maven-java-bdd-demo/pom.xml --no-transfer-progress

      - name: Setup node Build bdd-ui
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Build bdd-ui/feature-file-helper-front-end
        run: |
          pushd bdd-ui/feature-file-helper-front-end
          npm install -g @angular/cli
          npm install
          ng build
          popd

      - name: Build bdd-ui/feature-file-helper-back-end
        run: |
          pushd bdd-ui/feature-file-helper-back-end
          npm install
          popd
