# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven for pam-quick-examples

on:
  push:
    paths:
      - .github/workflows/mvn-pam-quick-examples.yaml
      - pam-quick-examples/**
  pull_request:
    paths:
      - .github/workflows/mvn-pam-quick-examples.yaml
      - pam-quick-examples/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-pam-quick-examples-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          repositories: '[{ "id": "redhat-ga-repository", "url": "https://maven.repository.redhat.com/ga" }]'
          plugin_repositories: '[{ "id": "redhat-ga-repository", "url": "https://maven.repository.redhat.com/ga" }]'

      - name: Run ShellCheck
        if: matrix.os == 'ubuntu-latest'
        uses: ludeeus/action-shellcheck@master
        with:
          ignore: bcgithook bdd-ui kogito-quick-start-workshop offliner-maven-plugin pam-eap-setup pam-vagrant

      - name: Build pam-quick-examples
        run: |
          pushd pam-quick-examples/dmn-example1
          bash build.sh
          popd

          pushd pam-quick-examples/dmn-example2
          bash build.sh
          popd

          pushd pam-quick-examples/dmn-example3
          bash build.sh
          popd

          pushd pam-quick-examples/dmn-example4
          bash build.sh
          popd

          pushd pam-quick-examples/dmn-example5
          bash build.sh
          popd

          pushd pam-quick-examples/dmn-example6
          bash build.sh
          popd